# Generated by Django 4.2 on 2023-04-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('option_one', models.BooleanField()),
                ('option_one_lower', models.IntegerField()),
                ('option_one_upper', models.IntegerField()),
                ('option_two', models.BooleanField()),
                ('option_two_lower', models.IntegerField()),
                ('option_two_upper', models.IntegerField()),
                ('option_three', models.BooleanField()),
                ('option_three_lower', models.IntegerField()),
                ('option_three_upper', models.IntegerField()),
                ('option_four', models.BooleanField()),
                ('option_four_lower', models.IntegerField()),
                ('option_four_upper', models.IntegerField()),
                ('option_five', models.BooleanField()),
                ('option_five_lower', models.IntegerField()),
                ('option_five_upper', models.IntegerField()),
            ],
        ),
    ]
